# Generated by Django 6.0 on 2025-12-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_column='Title', null=True, verbose_name='Title')),
                ('url_handle', models.TextField(blank=True, db_column='URL handle', null=True, verbose_name='URL handle')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='Description')),
                ('vendor', models.TextField(blank=True, db_column='Vendor', null=True, verbose_name='Vendor')),
                ('product_category', models.TextField(blank=True, db_column='Product category', null=True, verbose_name='Product category')),
                ('type', models.TextField(blank=True, db_column='Type', null=True, verbose_name='Type')),
                ('tags', models.TextField(blank=True, db_column='Tags', null=True, verbose_name='Tags')),
                ('published_on_online_store', models.TextField(blank=True, db_column='Published on online store', null=True, verbose_name='Published on online store')),
                ('status', models.TextField(blank=True, db_column='Status', null=True, verbose_name='Status')),
                ('sku', models.TextField(blank=True, db_column='SKU', null=True, verbose_name='SKU')),
                ('barcode', models.TextField(blank=True, db_column='Barcode', null=True, verbose_name='Barcode')),
                ('option1_name', models.TextField(blank=True, db_column='Option1 name', null=True, verbose_name='Option1 name')),
                ('option1_value', models.TextField(blank=True, db_column='Option1 value', null=True, verbose_name='Option1 value')),
                ('option2_name', models.TextField(blank=True, db_column='Option2 name', null=True, verbose_name='Option2 name')),
                ('option2_value', models.TextField(blank=True, db_column='Option2 value', null=True, verbose_name='Option2 value')),
                ('option3_name', models.TextField(blank=True, db_column='Option3 name', null=True, verbose_name='Option3 name')),
                ('option3_value', models.TextField(blank=True, db_column='Option3 value', null=True, verbose_name='Option3 value')),
                ('price', models.TextField(blank=True, db_column='Price', null=True, verbose_name='Price')),
                ('price_international', models.TextField(blank=True, db_column='Price / International', null=True, verbose_name='Price / International')),
                ('compare_at_price', models.TextField(blank=True, db_column='Compare-at price', null=True, verbose_name='Compare-at price')),
                ('compare_at_price_international', models.TextField(blank=True, db_column='Compare-at price / International', null=True, verbose_name='Compare-at price / International')),
                ('cost_per_item', models.TextField(blank=True, db_column='Cost per item', null=True, verbose_name='Cost per item')),
                ('charge_tax', models.TextField(blank=True, db_column='Charge tax', null=True, verbose_name='Charge tax')),
                ('tax_code', models.TextField(blank=True, db_column='Tax code', null=True, verbose_name='Tax code')),
                ('unit_price_total_measure', models.TextField(blank=True, db_column='Unit price total measure', null=True, verbose_name='Unit price total measure')),
                ('unit_price_total_measure_unit', models.TextField(blank=True, db_column='Unit price total measure unit', null=True, verbose_name='Unit price total measure unit')),
                ('unit_price_base_measure', models.TextField(blank=True, db_column='Unit price base measure', null=True, verbose_name='Unit price base measure')),
                ('unit_price_base_measure_unit', models.TextField(blank=True, db_column='Unit price base measure unit', null=True, verbose_name='Unit price base measure unit')),
                ('inventory_tracker', models.TextField(blank=True, db_column='Inventory tracker', null=True, verbose_name='Inventory tracker')),
                ('inventory_quantity', models.TextField(blank=True, db_column='Inventory quantity', null=True, verbose_name='Inventory quantity')),
                ('continue_selling_when_out_of_stock', models.TextField(blank=True, db_column='Continue selling when out of stock', null=True, verbose_name='Continue selling when out of stock')),
                ('weight_value_grams', models.TextField(blank=True, db_column='Weight value (grams)', null=True, verbose_name='Weight value (grams)')),
                ('weight_unit_for_display', models.TextField(blank=True, db_column='Weight unit for display', null=True, verbose_name='Weight unit for display')),
                ('requires_shipping', models.TextField(blank=True, db_column='Requires shipping', null=True, verbose_name='Requires shipping')),
                ('fulfillment_service', models.TextField(blank=True, db_column='Fulfillment service', null=True, verbose_name='Fulfillment service')),
                ('product_image_url', models.TextField(blank=True, db_column='Product image URL', null=True, verbose_name='Product image URL')),
                ('image_position', models.TextField(blank=True, db_column='Image position', null=True, verbose_name='Image position')),
                ('image_alt_text', models.TextField(blank=True, db_column='Image alt text', null=True, verbose_name='Image alt text')),
                ('variant_image_url', models.TextField(blank=True, db_column='Variant image URL', null=True, verbose_name='Variant image URL')),
                ('gift_card', models.TextField(blank=True, db_column='Gift card', null=True, verbose_name='Gift card')),
                ('seo_title', models.TextField(blank=True, db_column='SEO title', null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, db_column='SEO description', null=True, verbose_name='SEO description')),
                ('google_shopping_google_product_category', models.TextField(blank=True, db_column='Google Shopping / Google product category', null=True, verbose_name='Google Shopping / Google product category')),
                ('google_shopping_gender', models.TextField(blank=True, db_column='Google Shopping / Gender', null=True, verbose_name='Google Shopping / Gender')),
                ('google_shopping_age_group', models.TextField(blank=True, db_column='Google Shopping / Age group', null=True, verbose_name='Google Shopping / Age group')),
                ('google_shopping_mpn', models.TextField(blank=True, db_column='Google Shopping / MPN', null=True, verbose_name='Google Shopping / MPN')),
                ('google_shopping_adwords_grouping', models.TextField(blank=True, db_column='Google Shopping / AdWords Grouping', null=True, verbose_name='Google Shopping / AdWords Grouping')),
                ('google_shopping_adwords_labels', models.TextField(blank=True, db_column='Google Shopping / AdWords labels', null=True, verbose_name='Google Shopping / AdWords labels')),
                ('google_shopping_condition', models.TextField(blank=True, db_column='Google Shopping / Condition', null=True, verbose_name='Google Shopping / Condition')),
                ('google_shopping_custom_product', models.TextField(blank=True, db_column='Google Shopping / Custom product', null=True, verbose_name='Google Shopping / Custom product')),
                ('google_shopping_custom_label_0', models.TextField(blank=True, db_column='Google Shopping / Custom label 0', null=True, verbose_name='Google Shopping / Custom label 0')),
                ('google_shopping_custom_label_1', models.TextField(blank=True, db_column='Google Shopping / Custom label 1', null=True, verbose_name='Google Shopping / Custom label 1')),
                ('google_shopping_custom_label_2', models.TextField(blank=True, db_column='Google Shopping / Custom label 2', null=True, verbose_name='Google Shopping / Custom label 2')),
                ('google_shopping_custom_label_3', models.TextField(blank=True, db_column='Google Shopping / Custom label 3', null=True, verbose_name='Google Shopping / Custom label 3')),
                ('google_shopping_custom_label_4', models.TextField(blank=True, db_column='Google Shopping / Custom label 4', null=True, verbose_name='Google Shopping / Custom label 4')),
            ],
            options={
                'db_table': 'product_upload_row',
            },
        ),
    ]
