# Generated by Django 6.0 on 2025-12-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productuploadrow',
            table=None,
        ),
    ]
