# Generated by Django 6.0 on 2025-12-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productuploadrow_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploadrow',
            name='seo_description',
            field=models.CharField(blank=True, db_column='SEO description', max_length=320, null=True, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='productuploadrow',
            name='seo_title',
            field=models.CharField(blank=True, db_column='SEO title', max_length=70, null=True, verbose_name='SEO title'),
        ),
    ]
