# Generated by Django 6.0 on 2025-12-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productuploadrow_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadrow',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Upload time'),
        ),
    ]
