# Generated by Django 6.0 on 2025-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productuploadrow_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploadrow',
            name='url_handle',
            field=models.CharField(blank=True, db_column='URL handle', max_length=255, null=True, verbose_name='URL handle'),
        ),
    ]
