# Generated by Django 6.0 on 2025-12-17

from django.db import migrations, models
import django.db.models.deletion


def _migrate_vendor_text_to_fk(apps, schema_editor):
    Vendor = apps.get_model("products", "Vendor")
    ProductUploadRow = apps.get_model("products", "ProductUploadRow")

    cache: dict[str, int] = {}

    qs = ProductUploadRow.objects.all().values_list("pk", "vendor")
    for pk, vendor_text in qs.iterator():
        name = (vendor_text or "").strip()
        if not name:
            continue
        vendor_id = cache.get(name)
        if vendor_id is None:
            vendor, _created = Vendor.objects.get_or_create(name=name)
            vendor_id = vendor.pk
            cache[name] = vendor_id
        ProductUploadRow.objects.filter(pk=pk).update(vendor_fk_id=vendor_id)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productuploadrow_url_handle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="productuploadrow",
            name="vendor_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_rows",
                to="products.vendor",
            ),
        ),
        migrations.RunPython(_migrate_vendor_text_to_fk, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="productuploadrow",
            name="vendor",
        ),
        migrations.RenameField(
            model_name="productuploadrow",
            old_name="vendor_fk",
            new_name="vendor",
        ),
        migrations.AlterField(
            model_name="productuploadrow",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                db_column="Vendor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_rows",
                to="products.vendor",
                verbose_name="Vendor",
            ),
        ),
    ]

