# Generated by Django 6.0 on 2025-12-17

from django.db import migrations, models
import django.db.models.deletion


def _normalize_and_dedupe_sku(apps, schema_editor):
    ProductUploadRow = apps.get_model("products", "ProductUploadRow")

    # Normalize SKU values (trim, empty->NULL, truncate to 255) and ensure uniqueness.
    seen: set[str] = set()
    for pk, sku in ProductUploadRow.objects.all().values_list("pk", "sku").iterator():
        normalized = (sku or "").strip()
        if not normalized:
            ProductUploadRow.objects.filter(pk=pk).update(sku=None)
            continue

        if len(normalized) > 255:
            normalized = normalized[:255]

        if normalized in seen:
            ProductUploadRow.objects.filter(pk=pk).update(sku=None)
            continue

        seen.add(normalized)
        if normalized != sku:
            ProductUploadRow.objects.filter(pk=pk).update(sku=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_vendor_model_and_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productuploadrow",
            name="sku",
            field=models.CharField(
                blank=True,
                db_column="SKU",
                db_index=True,
                max_length=255,
                null=True,
                unique=False,
                verbose_name="SKU",
            ),
        ),
        migrations.RunPython(_normalize_and_dedupe_sku, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productuploadrow",
            name="sku",
            field=models.CharField(
                blank=True,
                db_column="SKU",
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product_image_url",
                    models.TextField(blank=True, db_column="Product image URL", null=True, verbose_name="Product image URL"),
                ),
                (
                    "variant_image_url",
                    models.TextField(blank=True, db_column="Variant image URL", null=True, verbose_name="Variant image URL"),
                ),
                (
                    "image_position",
                    models.PositiveIntegerField(blank=True, db_column="Image position", null=True, verbose_name="Image position"),
                ),
                (
                    "image_alt_text",
                    models.TextField(blank=True, db_column="Image alt text", null=True, verbose_name="Image alt text"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="SKU",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productuploadrow",
                        to_field="sku",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "image_position"], name="products_pr_SKU_843d74_idx"),
        ),
    ]

