# Generated by Django 4.1.5 on 2025-12-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_images_and_unique_sku'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='ProductImage'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS products_productimage",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS products_productimage_images",  # safety for M2M if ever existed
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
