# Generated by Django 4.1.5 on 2025-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploadrow',
            name='charge_tax',
            field=models.BooleanField(blank=True, db_column='Charge tax', default=False, null=True, verbose_name='Charge tax'),
        ),
        migrations.AlterField(
            model_name='productuploadrow',
            name='continue_selling_when_out_of_stock',
            field=models.BooleanField(blank=True, db_column='Continue selling when out of stock', default=False, null=True, verbose_name='Continue selling when out of stock'),
        ),
        migrations.AlterField(
            model_name='productuploadrow',
            name='gift_card',
            field=models.BooleanField(blank=True, db_column='Gift card', default=False, null=True, verbose_name='Gift card'),
        ),
        migrations.AlterField(
            model_name='productuploadrow',
            name='published_on_online_store',
            field=models.BooleanField(blank=True, db_column='Published on online store', default=False, null=True, verbose_name='Published on online store'),
        ),
        migrations.AlterField(
            model_name='productuploadrow',
            name='requires_shipping',
            field=models.BooleanField(blank=True, db_column='Requires shipping', default=False, null=True, verbose_name='Requires shipping'),
        ),
    ]
